apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://terraform-1d2d648586836487f47b2c004f.cri0y2q6obei.ap-south-1.rds.amazonaws.com:5432/food_waste_db?sslmode=require"
  SPRING_JPA_SHOW_SQL: "false"